name: Publish Game to Actions

on:
  workflow_dispatch:

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: netspace
  PROJECT_PATH: GodotWorkspace

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
  build:
    name: build-web
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" ../build/web/index.html
      - name: Add Workaround SharedArrayBuffer
          # Workaround for SharedArrayBuffer support on GitHub Pages
          # See: https://github.com/godotengine/godot-docs/issues/7084
        run: |
          cd build/web
          curl -fsSL https://github.com/gzuidhof/coi-serviceworker/raw/master/coi-serviceworker.js > coi-serviceworker.js
          sed -i 's#\(		<script src="index.js"></script>\)#		<script src="coi-serviceworker.js"></script>\n\1#g' index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: netspace-web
          path: build/web/*
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.