name: Publish Game to Actions

on:
  push:
    branches:
      - main
    paths:
      - 'GodotWorkspace/**'
  workflow_dispatch:

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: netspace
  PROJECT_PATH: GodotWorkspace

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
  build:
    name: build-web
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web Server Release" ../build/web/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: netspace-web-${{ github.sha }}
          path: build/web
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action